[package]
    name    = "my-jira"
    version = "0.1.0"

    edition = "2021"
    publish = false

[dependencies]
    anyhow     = "1.*"
    serde      = "1.*"
    serde_json = "1.*"
    tempfile   = "3.*"
